# Generated by Django 2.1.5 on 2020-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='content',
            field=models.TextField(default=1, verbose_name='Resumen'),
            preserve_default=False,
        ),
    ]
