# Generated by Django 2.1.5 on 2020-04-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grua', '0002_serie_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grua',
            old_name='serie',
            new_name='category',
        ),
    ]
