# Generated by Django 2.0.5 on 2020-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grua', '0004_auto_20200413_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grua',
            old_name='category',
            new_name='categories',
        ),
    ]
