# Generated by Django 2.0.5 on 2020-04-21 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grua', '0006_auto_20200413_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grua',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Resumen'),
        ),
    ]
